### PR TITLE
Problem with config.NATPORT

### PR DESCRIPTION
**Pull request by TTimo**
I ran into a problem with using NATPORT=0, `config.NATPORT or None` turning into `None` when the value is 0, and subsequently failing on line 1119

I also had to add the `and nathost is not None` to leave `natport` set to `None` when not using `nathost` at all, as that was breaking things like `pyro4-ns --host=172.31.3.54`

I think a slightly different/better fix may be to set the default for `config.NATPORT` to `None` as well.

### CODE REVIEW

**Comment by irmen** [comment]
How do I reproduce the problem you encountered? NATPORT is 0 by default.

**Comment by TTimo** [comment]
I started a daemon with `PYRO_NATHOST=myhost.company.com PYRO_NATPORT=0` environment variables:

```
20:29:29 [p=808, t=140528101267200, CRITICAL, presence] Stopping
Traceback (most recent call last):
[..]
  File "/home/ubuntu/RoomoredBackend/src/roomored_backend/utils/pyro.py", line 61, in register
    daemon = Pyro4.Daemon()
  File "/usr/local/lib/python3.5/dist-packages/Pyro4-4.75-py3.5.egg/Pyro4/core.py", line 1121, in __init__
    raise ValueError("must provide natport with nathost")
ValueError: must provide natport with nathost
```

**Comment by irmen** [comment]
Thank you!  
But what is the purpose of the NATPORT=0?  Do you want to get a random port there? How can you use that for a NAT configuration if you don't know the port number upfront?

**Comment by TTimo** [comment]
I was using NATPORT based on the documentation:

https://pyro4.readthedocs.io/en/stable/tipstricks.html?highlight=NATPORT

"In some situations the NAT simply is configured to pass through any port one-to-one to another host behind the NAT router/firewall. Pyro facilitates this by allowing you to set the natport to 0, in which case Pyro will replace it by the internal port number."

**Comment by irmen** [comment]
Wow, you're totally right, I should have read my own documentation!  :confused: 
I will look into the details about this.

**Comment by irmen** [comment]
I fixed the docs and the unit test for this.
The change has also been made in Pyro5 now.

**Comment by TTimo** [comment]
Good stuff. I'm pretty happy with Pyro4 so far. I think the main drawback I've run into is how many TCP connections out of different ports it wants to open for communication.

I was initially hoping everything could be multiplexed into a single incoming SSL connection into our backend in order to connect in remote systems, but now I'm leaning towards VPN'ing them..

**Comment by irmen** [comment]
would this example help perhaps? https://github.com/irmen/Pyro4/tree/master/examples/blob-dispatch

**Comment by TTimo** [comment]
Thanks for the link. Based on this example and  https://pyro4.readthedocs.io/en/stable/tipstricks.html#efficient-dispatchers-or-gateways-that-don-t-de-reserialize-messages, I think I see how I could implement a proxy that listens on a single port and dispatches calls to the various objects, but I don't think it would be reasonable for me to undertake the implementation at this time.

It would be nice if this was a core feature though. Maybe say in Pyro5?

Maybe something leveraging libjingle [1] - once a connection is established between the two sides via libjingle - Pyro would then behave as if the processes where all sitting next to each other on a LAN with no firewalls, NATs etc.

[1] https://developers.google.com/talk/libjingle/developer_guide

**Comment by irmen** [comment]
It is already possible to create a pyro daemon and proxy on an externally created, already connected socket. You pass that as the connected_socket parameter to the init method.

This still doesn't make it possible to have one incoming multiplexed server port, but it also seems slightly relevant in this discussion

**Pull request merged**
