### PR TITLE
Dill support

### PR DESCRIPTION
**Pull request by Peque**
I start this pull request to discuss the possibility of supporting [Dill](https://github.com/uqfoundation/dill) serialization.

I would really appreciate any feedback/guidance, as I have little experience with Pyro4. If it leads to the acceptance of this feature request, I will try to make the necessary changes.

### CODE REVIEW

**Comment by irmen** [comment]
The basics look okay, however there are several things missing:
- updates to the documentation mentioning the new serializer format
- unit tests that mirror the existing serializer tests

Also, what is the big plus of adding support for Dill?   (i.e. why would we bother adding this)

**Comment by Peque** [comment]
This is a plus for me (client):

```python
import Pyro4
Pyro4.config.SERIALIZERS_ACCEPTED.add('dill')
Pyro4.config.SERIALIZER = 'dill'


if __name__ == '__main__':

    def power(x):
        return x * x

    proxy = Pyro4.Proxy("PYRONAME:test")

    print(proxy.test(power))
    print(proxy.test(lambda x: x ** 3))
```

If you want to try it, here is the server code:

```python
import Pyro4
Pyro4.config.SERIALIZERS_ACCEPTED.add('dill')
Pyro4.config.SERIALIZER = 'dill'


class Test(object):
    def test(self, x):
        return x(2)


if __name__ == '__main__':

    daemon = Pyro4.Daemon()
    ns = Pyro4.locateNS()
    uri = daemon.register(Test)
    ns.register("test", uri)

    print("Ready.")
    daemon.requestLoop()
```

And the name server code:

```python
import Pyro4
Pyro4.config.SERIALIZERS_ACCEPTED.add('dill')
Pyro4.config.SERIALIZER = 'dill'


Pyro4.naming.startNSloop()
```

I see `dill` as a more capable alternative to `pickle`. Whether this plus is big enough to bother adding Dill support is not up to me to decide! (you tell me) :wink:

If you agree in supporting Dill I will try to complete the pull request with updated documentation and tests.

**Comment by irmen** [comment]
Ah, you can transmit functions and other things that pickle can't. Nifty. 

Go ahead with the feature!  But (now I know that it is an even more capable serializer than pickle) we need to make sure that in the changes in the documentation, dill is mentioned in all security warnings as well (next to pickle).

**Comment by Peque** [comment]
In `requirements.txt` there is the `serpent` module. `dill` is not part of Python either, but I guess it could be left out of the requirements (you can optionally install it if you are going to use dill). So I have left the `requirements.txt` file untouched. Do you agree?

Also, I guess `dill` could also be used with Flame. However, I have not tested that, so I have not touched `flame.rst` either.

I still need to have a look at the tests before completing this pull request.

**Comment by Peque** [comment]
Some basic tests have been added to test dill serialization. Please, have a look at it when you have some time and tell me if I can improve the pull request.

Although dill is not set in `requirements.txt`, `run_testsuite.py` will raise an exception if not present. Is it fine with you?

**Comment by Peque** [comment]
I must be doing something wrong, as the Travis build is failing. It seems it is only installing `serpent`, but not `dill` in the test virtual environment. The `tox.ini` file looks like this:

```
[...]
[testenv]
deps =
    serpent>=1.11
    dill>=0.2.4
[...]
```

When I run `tox` in my machine it works as expected: it installs both dependencies as set in `tox.ini` file.

```
$ tox
[...]
py34 installdeps: -rrequirements.txt, dill==0.2.3
[...]
```

However, when tests are run by Travis, it seems it executes `pip install -e .` and that results in `serpent` being installed (perhaps because it is in `requirements.txt`) but in `dill` not being installed.

Any idea?

**Comment by Peque** [comment]
Some basic tests have been added to test dill serialization. Please, have a look at it when you have some time and tell me if I can further improve the pull request.

**Comment by Peque** [comment]
Right now it seems [2.7, 3.3 and 3.5 are passing, although 3.4 is not](https://travis-ci.org/irmen/Pyro4/builds/115914886). In my machine, with CPython 3.4 everything works as expected.

screenshot from 2016-03-14 18-37-33

Do you know why could this be happening? could you either try to pass the tests in your machine or [have a look at the 3.4 log](https://travis-ci.org/irmen/Pyro4/jobs/115914889) in case you see something familiar?

Pypy is not passing the tests, but I can easily reproduce that in my machine. I'll take a look at it, although I don't have any experience with `pypy`. It may be [dill itself](https://github.com/uqfoundation/dill/issues/73). In that case would it be blocking for the pull request? or could it be added knowing that dill will only work when using CPython?

**Comment by irmen** [comment]
Looking quite good already, will have a look at the problems

**Comment by Peque** [comment]
Commit  [3fb4427](https://github.com/irmen/Pyro4/commit/3fb4427e25d6d98b878dfdb8c81bc7a0afd4a9d1) fixes problems with PyPy + dill. Although the fix is so dirty that I feel a bit embarrassed asking you to merge this, so I would understand if you did not want to... The worst  thing is that avoiding tests while using PyPy (i.e. `@unittest.skipIf(platform.python_implementation() == 'PyPy', ...)`) is not sufficient. Simply importing dill, at any point, while using PyPy will make the tests fail (that is why I had to add so many platform checks).

The good thing is that it is only a single commit, which could be easily reverted when dill fixes its PyPy compatibility issues. If you decide to merge this pull request, I could open an issue here in Github. I am already subscribed to updates on dill's PyPy compatibility changes, so once they release a fix, I will revert the dirty hack here in Pyro.

There is, however, another problem, which is Travis failing with CPython 3.4. Apparently [it was a bug in CPython](http://bugs.python.org/issue23094) which [is already fixed](https://hg.python.org/cpython/rev/d5e13b74d377). That would explain why you in Windows and me in Linux are not having problems when running the tests with Python 3.4.

**Comment by irmen** [comment]
I've asked support at travis if they plan on a possible python 3.4 version upgrade.
The changes to avoid running certain tests on pypy are ugly but I'm okay with them -- I used to have a dozen similar checks for jython in the code... :neutral_face:

**Comment by Peque** [comment]
You are right about:

> Shouldn't this only skip the loop for pypy if ser_id is the dill serializer?

I fixed it and [packed every PyPy+dill-related dirty hack in a single commit again](https://github.com/irmen/Pyro4/pull/107/commits/66fb6a10d81b794525d4f40510d29aa64e66ca10) (so that it can be easily reverted in the future).

Also, it seems that [Python 3.4.3 is available in Travis](https://github.com/travis-ci/travis-ci/issues/4632#issuecomment-128837176), although [not documented](https://github.com/travis-ci/travis-ci/issues/4859). So I have [set 3.4.3 in `.travis.yml`](https://github.com/irmen/Pyro4/pull/107/commits/9addd252dfcda2f211baa908e694cc2ee08424e2). It seems all tests are finally passing.

**Comment by irmen** [comment]
Thanks for the work, it's looking pretty good. Will do a full review shortly, and merge it.

**Comment by Peque** [comment]
Thanks to you for considering this proposal, for taking the time to review my changes and for guiding me throughout the process.

**Pull request merged**
