### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/irmen/Pyro4/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/irmen/Pyro4).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by irmen** [comment]
Hm, there are too many false positives in the alerts.   (which always is a problem when linting code)

**Comment by xcorail** [comment]
Hi @irmen 
Could you please share the alerts that you suspect to be false positives?
Thanks

**Comment by xcorail** [comment]
Hi @irmen 

Thanks a lot for taking the time to do this feedback. Much appreciated.
I will pass this to my python-analysis colleagues, so that they can check the false positives.

> all errors reported on code from the examples directory

Indeed. LGTM tries to exclude automatically some files (tests, generated, ...) but cannot find all of them. You can easily adapt the configuration of your project so that this directory is excluded, and the alerts won't show up again. See [here](https://lgtm.com/help/lgtm/customizing-file-classification)

> the "Except block directly handles BaseException." is not applicable in Pyro's case

Because the activity of writing code is complex, you are right that code linters cannot understand the purpose behind a specific code, only the developer can say whether this alert matters to him/her or not, whether this code was done on purpose or not ... You can decide to exclude this alert for all Pyro at the level of the [project configuration](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file#queries), when your code contains such special stuff that makes the alert irrelevant in your context. 

Thanks again!

**Comment by xcorail** [comment]
Hi @irmen 

1. I confirm that the "Missing call to init" is a false positive, which has been [reported last month](https://discuss.lgtm.com/t/python-3-false-positives-with-init/1129), and which will be fixed on our end.
2. The "Variable defined multiple times" happens to be a true positive. Indeed, if the try block fails, the variable won't be assigned ... but in this case, this variable will never get used anyway, so the first
definition is superfluous
3. I can submit a PR to adjust the LGTM project configuration and exclude the examples directory from the analysis. It's just a lgtm.yml file. Are you interested?   

Thanks

**Comment by irmen** [comment]
@xcorail yes I am interested in that. Thanks.

**Comment by xcorail** [comment]
@irmen LGTM runs analysis on all commits, but with the given priority:
1. Pull requests 
2. HEAD commit of all public projects
3. all commits from history, most recent first

I realize that I forgot to mention that you can activate very easily PR integration [here](https://lgtm.com/projects/g/irmen/Pyro4/ci/), if you want LGTM to report any new problem (or new fix) directly in the PR.

**Comment by xcorail** [comment]
Hi @irmen 

I pushed the configuration change on the same branch (by mistake). Sorry.
Please tell me if you prefer that I revert and re-propose the PR limited to the configuration change

**Comment by irmen** [comment]
@xcorail it hasn't rechecked the repo yet, is there a delay of some sort as well?

**Comment by xcorail** [comment]
hm ... let me dig into this ...

**Comment by xcorail** [comment]
@irmen 
Yes, sorry, there is indeed a delay: we poll new commits once a day. So yesterday's poll certainly happened before the commits, and they will be taken today

We usually recommend to activate PR integration, we think it's the most effective usage of LGTM (hence the name) to prevent problems from hitting the master. Here there is no delay.

We think the delayed analysis of commits (new and past) is more useful for analysing globally your code's writing process, generating insights on your process and your contributors, that you could use for more global improvements; such as these code quality badges, but also some exciting things that our data science team is discovering. For example:
* https://lgtm.com/blog/emotions_in_commit_messages
* https://lgtm.com/blog/code_quality_1

But also how to link some code attributes and measures to 'time to write a new feature' ... This one I would have loved to have in my former job, to convince everyone of the necessity of controlling technical debt!

Well ... I become too chatty here sorry ... :-) I am quite excited by this stuff.
Cheers

**Comment by irmen** [comment]
Pyro is almost all a one man show, mine :)   While all these metrics certainly look nice and seem interesting, they're not as relevant in this project's context tbh.  For instance, there are hardly ever pull-requests happening.

**Comment by xcorail** [comment]
:)
Well, given its popularity, it's a good one man show.

**Pull request merged**
